apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata: 
  name: emicorp
  namespace: argocd
spec:
  description: Emicorp platform applications
  sourceRepos:
    - https://github.com/nvim-solutions/emicorp-org-devops-platform.git
    - https://github.com/nvim-solutions/emicorp-org-devops-helm-users-service.git
  destinations:
    - namespace: default
      server: https://kubernetes.default.svc
    - namespace: argocd
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'