{{- if .Values.sharedSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.sharedSecret.name }}
type: Opaque
stringData:
  DB_USERNAME: {{ .Values.auth.username | quote }}
  DB_PASSWORD: {{ .Values.auth.password | quote }}
{{- end }}
