image:
  repository: postgres
  tag: "15"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5432

auth:
  database: emicorp_db
  username: postgres
  password: postgres

sharedSecret:
  enabled: true
  name: service-secrets
