replicaCount: 1
image:
  repository: ghcr.io/nvim-solutions/users-service
  tag: "sha-15ae39c"
  pullPolicy: IfNotPresent
ingress:
  enabled: true
  host: users.emicorp.local
config:
  DB_HOST: postgres
  DB_PORT: "5432"
  DB_NAME: emicorp_db
